swagger: "2.0"
info:
  version: "1.0.0"
  title: "news generator"
host: "master-gpt2-article-generator-ha-mulan.endpoint.ainize.ai" 
basePath: "/api/"
schemes:
- "https"
- "http"
consumes:
  - string
produces:
  - string
paths:
  /:
    get:
      tags:
      - "make article"
      summary: "create article"
      description: "plz input title of article and it's contents"
      produces:
      - "string"
      - "application/xml"
      - "application/json"
      parameters:
      - name: "title"
        type: 'string'
        in: "query"
        description: "title of article"
        required: true
        items:
          type: "string"
          default: "trump"
      - name: "content"
        type: 'string'
        in: "query"
        description: "initial content of article"
        required: true
        items:
          type: "string"
          default: "war"
      responses:
        "200":
          description: "successful operation"



        "400":
          description: "Invalid status value"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"